### ISSUE TITLE
URL should be enclosed in quotes (RuntimeError: command failed (exitstatus=127))

### ISSUE THREAD

**Issue by romanbsd** [pdfkit/pdfkit#284]
When the url has some interesting characters, the command fails.
Our solution was to enclose the url in double quotes:
```ruby
class PDFKit::Source
  def to_s
    return %{"#{@source}"} if url?
    file? ? @source.path : @source
  end
end
```
The problem was manifesting itselt as:
RuntimeError: command failed (exitstatus=127)

And when tested locally with the problematic URL, it became evident that the wkhtmltopdf was not able to figure out what to do and was displaying the help.

**Comment by cdwort** [comment]
@romanbsd Thank you for bringing this issue to our attention. I intend to fix this in #312. So far, it's looking like it should go though - no unintentional side-effects. (Quite the small miracle that is)

Thanks again!

**Comment by cdwort** [comment]
Oof. Well, record time to disappointment. Putting quotes around the URL leaves places makes any shell or URI escaping that we do become literal. I'm leaving this open until #312 resolves and we can see where we ended up.

**Comment by cdwort** [comment]
This is fixed in master and will be out with the next release. Thanks for bringing this up!

**Comment by lacostenycoder** [comment]
I'm still getting this with version 0.8.2, Ruby 2.1.5, Rails 4.2 .  Any ideas?

**Comment by cdwort** [comment]
Hey @lacostenycoder 

Usually what you'll need to do is run the wkhtmltopdf command on the relevant setup and see what the output is. 

If you find the place in your code that you're running `PDFKit.new`, you'll want to do something like this:

```
kit = PDFKit.new(your_arguments_when_it_fails)
kit.command
```

Take the output of that and run it manually. That will get you whatever information wkhtmltopdf can get you. Their error messages and documentation have improved lately!

Good luck! If you find something that's relevant to PDFKit, we'd love to hear back.
